project:
  type: book

book:
  title: "Healthcare Decision Intelligence"
  author: "Chandan Kaur"
  chapters:
    - Book_Cover.qmd
    - index.qmd
    - Part_1.qmd
    - modules/01-Counts-vs-Rates.qmd
    - modules/02-Mean-vs-Median.qmd
    - modules/03-Correlation-vs-Causation.qmd
    - modules/04-Variation-&-Distributions.qmd
    - modules/05-Standardisation-&-Fair-Comparison.qmd
    - modules/06-How-to-Read-a-Dashboard.qmd
    - modules/07-Theory-Of-Change-&-Logic-Models.qmd
    - modules/08-Thinking-About-Evidence-&-Evaluation.qmd
    - modules/09-Evaluating-Methods-in-Practice.qmd
    - modules/10-Risk-Probability-Uncertainty.qmd
    - modules/11-Common-Analytical-Traps-&-Data-Fallacies.qmd
    - Part_2.qmd
    - modules/12-Demand_Capacity_Operational_Flow.qmd
    - modules/13-Data-Quality-Assurance-Trustworthy-Data.qmd
    - modules/14-Designing-Better-Healthcare-Pathways.qmd
    - modules/15-Health-Economics-&-Value-in-Healthcare-Decision-Making.qmd
    - Project.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    html-math-method: mathjax
    include-in-header: include.html
